services:
  # 1. Local Database
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - '27017:27017'
    volumes:
      - local_mongo_data:/data/db

  # 2. Backend
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/v1
    depends_on:
      - backend

volumes:
  local_mongo_data:
